export const userInputs = [
    {
      id: 1,
      label: "Username",
      type: "text",
      placeholder: "john_doe",
    },
    {
      id: 2,
      label: "Name and surname",
      type: "text",
      placeholder: "John Doe",
    },
    {
      id: 3,
      label: "Email",
      type: "mail",
      placeholder: "john_doe@gmail.com",
    },
    {
      id: 4,
      label: "Phone",
      type: "text",
      placeholder: "+1 234 567 89",
    },
    {
      id: 5,
      label: "Password",
      type: "password",
    },
    {
      id: 6,
      label: "Address",
      type: "text",
      placeholder: "Elton St. 216 NewYork",
    },
    {
      id: 7,
      label: "Country",
      type: "text",
      placeholder: "USA",
    },
  ];
  
  export const productInputs = [
    {
      id: 1,
      label: "Nombre",
      type: "text",
      name:'name',
      placeholder: "Name",
    },
    {
      id: 2,
      label: "Description",
      type: "text",
      name:'description',
      placeholder: "Description",
    },
    
    {
      id: 4,
      label: "Price",
      type: "number",
      name:'price',
      placeholder: "100",
    },
    {
      id: 5,
      label: "Stock",
      type: "number",
      name:'stock',
      placeholder: "In stock",
    },
    
    {
      id: 6,
      label: "Material",
      type: "text",
      name:'material',
      placeholder: "Material",
      error: "errors.material"
    },
    {
      id: 7,
      label: "Released",
      type: "text",
      name:'released',
      placeholder: "Released",
    },
    {
      id: 8,
      label: "Designer",
      type: "text",
      name:'designer',
      placeholder: "Designer",
    },
    {
      id: 9,
      label: "Details",
      type: "text",
      name:'details',
      placeholder: "Details",
    },
    {
      id: 10,
      label: "Shoe condition",
      type: "text",
      name:'shoe_condition',
      placeholder: "Condition",
    },
    {
      id: 11,
      label: "Rating",
      type: "number",
      name:'rating',
      placeholder: "5",
    },

  ];
 
  export const sizes = [
    '10',
    '10.5',
    '11',
    '11.5',
    '12',
    '12.5',
    '13',
    '13.5',
    '14',
    '14.5',
    '15',
    '15.5',
    '16',
    '16.5',
    '17',
    '17.5',
    '18',
    '3.5',
    '4',
    '4.5',
    '5',
    '5.5',
    '6',
    '6.5',
    '7',
    '7.5',
    '8',
    '8.5',
    '9',
    '9.5',
    '3',
    '19',
    
  ]
