export const DELETE_CARRITO = "DELETE_CARRITO";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_SHOES = "GET_ALL_SHOES";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_COLORS = "GET_ALL_COLORS";
export const GET_ALL_GENDERS = "GET_ALL_GENDERS";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";

export const GET_ALL_ORDERS_USER = "GET_ALL_ORDERS_USER";

export const GET_ALL_USER_REVIEWS = "GET_ALL_USER_REVIEWS";

export const GET_SHOES_DETAILS = "GET_SHOES_DETAILS";
export const CLEAN_DETAIL = "CLEAN_DETAIL";

export const GET_FILTERS_CATEGORY = "GET_FILTERS_CATEGORY";
export const GET_FILTERS_BRANDS = "GET_FILTERS_BRANDS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const GET_FILTERS_SEARCHBAR = "GET_FILTERS_SEARCHBAR";

export const GET_ADD_CARRITO = "GET_ADD_CARRITO";
export const DELETE_PRODUCT_CARRITO = "DELETE_PRODUCT_CARRITO";
export const CHANGE_AMOUNT_PRODUCT = "CHANGE_AMOUNT_PRODUCT";
export const GET_PRODUCTS_FROM_STORAGE = "GET_PRODUCTS_FROM_STORAGE";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const DELETE_QUESTIONS = "DELETE_QUESTIONS";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_SHOES = "CREATE_SHOES";
export const CREATE_CATEGORIES = "CREATE_CATEGORIES";
export const CREATE_GENDERS = "CREATE_GENDERS";
export const CREATE_COLORS = "CREATE_COLORS";
export const CREATE_BRANDS = "CREATE_BRANDS";
export const CREATE_REVIEW = "CREATE_REVIEW";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

export const CREATE_ORDEN = "CREATE_ORDEN";
export const UPDATE_ORDEN = "UPDATE_ORDEN";
